export const WORD_BANK = [
    // 4 LETTERS (EASY)
    { word: "DATA", hint: "Raw information processed by computers", category: "TECH", difficulty: 4 },
    { word: "NEON", hint: "A noble gas that glows when charged", category: "SCIENCE", difficulty: 4 },
    { word: "CODE", hint: "Instructions for a computer program", category: "TECH", difficulty: 4 },
    { word: "GRID", hint: "A network of lines that cross each other", category: "MATH", difficulty: 4 },
    { word: "BYTE", hint: "A unit of digital information (8 bits)", category: "TECH", difficulty: 4 },
    { word: "GAME", hint: "Activity engaged in for amusement", category: "GENERAL", difficulty: 4 },
    { word: "CITY", hint: "A large human settlement", category: "GENERAL", difficulty: 4 },
    { word: "DARK", hint: "Absence of light", category: "GENERAL", difficulty: 4 },
    { word: "GLOW", hint: "To emit light without flame", category: "GENERAL", difficulty: 4 },
    { word: "TECH", hint: "Short for technology", category: "TECH", difficulty: 4 },
    { word: "USER", hint: "A person who operates a computer", category: "TECH", difficulty: 4 },
    { word: "HACK", hint: "To gain unauthorized access", category: "CYBER", difficulty: 4 },
    { word: "CHIP", hint: "Small piece of semiconducting material", category: "TECH", difficulty: 4 },
    { word: "CORE", hint: "The central or most important part", category: "GENERAL", difficulty: 4 },
    { word: "DISK", hint: "A flat, thin, round object for storage", category: "TECH", difficulty: 4 },
    { word: "LINK", hint: "A connection between two things", category: "NET", difficulty: 4 },
    { word: "HOST", hint: "A computer connected to a network", category: "NET", difficulty: 4 },
    { word: "PING", hint: "To query a computer's availability", category: "NET", difficulty: 4 },
    { word: "ROOT", hint: "The highest directory in a hierarchy", category: "TECH", difficulty: 4 },
    { word: "BUG",  hint: "An error in a computer program", category: "TECH", difficulty: 4 },

    // 5 LETTERS (MEDIUM)
    { word: "CYBER", hint: "Relating to computers or robots", category: "CYBER", difficulty: 5 },
    { word: "ROBOT", hint: "A machine capable of carrying out actions", category: "SCI-FI", difficulty: 5 },
    { word: "LASER", hint: "A device that emits light amplification", category: "SCI-FI", difficulty: 5 },
    { word: "SPACE", hint: "The physical universe beyond earth", category: "SCI-FI", difficulty: 5 },
    { word: "VIRUS", hint: "Malicious software code", category: "TECH", difficulty: 5 },
    { word: "PIXEL", hint: "Smallest controllable element of a picture", category: "TECH", difficulty: 5 },
    { word: "POWER", hint: "Ability to do something or act", category: "GENERAL", difficulty: 5 },
    { word: "LOGIC", hint: "Reasoning conducted according to principles", category: "MATH", difficulty: 5 },
    { word: "DRONE", hint: "Unmanned aerial vehicle", category: "TECH", difficulty: 5 },
    { word: "CLOUD", hint: "Remote servers used for storage", category: "TECH", difficulty: 5 },
    { word: "STACK", hint: "Abstract data type (LIFO)", category: "TECH", difficulty: 5 },
    { word: "CACHE", hint: "Hardware or software component to store data", category: "TECH", difficulty: 5 },
    { word: "AUDIO", hint: "Sound, especially when recorded", category: "MEDIA", difficulty: 5 },
    { word: "VIDEO", hint: "Recording or broadcasting of visual images", category: "MEDIA", difficulty: 5 },
    { word: "PHONE", hint: "Device for voice communication", category: "TECH", difficulty: 5 },
    { word: "SMART", hint: "Having or showing intelligence", category: "GENERAL", difficulty: 5 },
    { word: "WATCH", hint: "Portable timepiece", category: "GENERAL", difficulty: 5 },
    { word: "BLOCK", hint: "Solid piece of hard material", category: "GENERAL", difficulty: 5 },
    { word: "CHAIN", hint: "Series of linked rings", category: "GENERAL", difficulty: 5 },
    { word: "TOKEN", hint: "Something serving as a visible representation", category: "TECH", difficulty: 5 },
    { word: "ALARM", hint: "An anxious awareness of danger", category: "GENERAL", difficulty: 5 },
    { word: "RESET", hint: "To set again or differently", category: "TECH", difficulty: 5 },
    { word: "INPUT", hint: "What is put in, taken in, or operated on", category: "TECH", difficulty: 5 },
    { word: "MODEL", hint: "A three-dimensional representation", category: "TECH", difficulty: 5 },
    { word: "QUERY", hint: "A question, often to a database", category: "TECH", difficulty: 5 },
    { word: "ERROR", hint: "A mistake", category: "GENERAL", difficulty: 5 },

    // 6 LETTERS (HARD)
    { word: "SYSTEM", hint: "A set of connecting things or parts", category: "TECH", difficulty: 6 },
    { word: "SERVER", hint: "A computer that provides data to others", category: "TECH", difficulty: 6 },
    { word: "MATRIX", hint: "An environment or material in which something develops", category: "SCI-FI", difficulty: 6 },
    { word: "GLITCH", hint: "A sudden, usually temporary malfunction", category: "TECH", difficulty: 6 },
    { word: "BINARY", hint: "Relating to, using, or expressed in a system of numerical notation that has 2 rather than 10 as a base", category: "MATH", difficulty: 6 },
    { word: "SCRIPT", hint: "Handwriting as distinct from print", category: "TECH", difficulty: 6 },
    { word: "DEVICE", hint: "A thing made or adapted for a particular purpose", category: "TECH", difficulty: 6 },
    { word: "FUTURE", hint: "The time or a period of time following the moment of speaking or writing", category: "GENERAL", difficulty: 6 },
    { word: "ENERGY", hint: "The strength and vitality required for sustained physical or mental activity", category: "PHYSICS", difficulty: 6 },
    { word: "SIGNAL", hint: "A gesture, action, or sound that is used to convey information", category: "TECH", difficulty: 6 },
    { word: "ACCESS", hint: "A means of approaching or entering a place", category: "TECH", difficulty: 6 },
    { word: "CLIENT", hint: "A desktop computer or workstation that is capable of obtaining information and applications from a server", category: "TECH", difficulty: 6 },
    { word: "DOMAIN", hint: "A distinct subset of the Internet with addresses sharing a common suffix", category: "TECH", difficulty: 6 },
    { word: "ROUTER", hint: "A device that forwards data packets to the appropriate parts of a computer network", category: "TECH", difficulty: 6 },
    { word: "PACKET", hint: "A block of data transmitted across a network", category: "TECH", difficulty: 6 },
    { word: "SCREEN", hint: "A flat panel or area on an electronic device on which images and data are displayed", category: "TECH", difficulty: 6 },
    { word: "SEARCH", hint: "Try to find something by looking or otherwise seeking carefully and thoroughly", category: "GENERAL", difficulty: 6 },
    { word: "STREAM", hint: "A continuous flow of data or instructions", category: "TECH", difficulty: 6 },
    { word: "UPDATE", hint: "Make (something) more modern or up to date", category: "TECH", difficulty: 6 },
    { word: "UPLOAD", hint: "Transfer (data) from one computer to another", category: "TECH", difficulty: 6 },

    // 7 LETTERS (EXPERT)
    { word: "NETWORK", hint: "A group or system of interconnected people or things", category: "TECH", difficulty: 7 },
    { word: "PROGRAM", hint: "Provide (a computer or other machine) with coded instructions for the automatic performance of a task", category: "TECH", difficulty: 7 },
    { word: "DISPLAY", hint: "Make a prominent exhibition of (something) in a place where it can be easily seen", category: "TECH", difficulty: 7 },
    { word: "STORAGE", hint: "The action or method of storing something for future use", category: "TECH", difficulty: 7 },
    { word: "DIGITAL", hint: "Expressed as series of the digits 0 and 1", category: "TECH", difficulty: 7 },
    { word: "VIRTUAL", hint: "Not physically existing as such but made by software to appear to do so", category: "TECH", difficulty: 7 },
    { word: "ANDROID", hint: "A robot with a human appearance", category: "SCI-FI", difficulty: 7 },
    { word: "CIRCUIT", hint: "A roughly circular line, route, or movement that starts and finishes at the same place", category: "TECH", difficulty: 7 },
    { word: "CONSOLE", hint: "A panel or unit accommodating a set of controls for electronic or mechanical equipment", category: "TECH", difficulty: 7 },
    { word: "DESKTOP", hint: "The working area of a computer screen regarded as representing a desktop", category: "TECH", difficulty: 7 },
    { word: "ELEMENT", hint: "A part or aspect of something abstract", category: "SCIENCE", difficulty: 7 },
    { word: "FIREWALL", hint: "A part of a computer system or network which is designed to block unauthorized access", category: "TECH", difficulty: 7 },
    { word: "GATEWAY", hint: "A device used to connect two different networks", category: "TECH", difficulty: 7 },
    { word: "KEYBOARD", hint: "A panel of keys that operate a computer or typewriter", category: "TECH", difficulty: 7 },
    { word: "MONITOR", hint: "An instrument or device used for observing, checking, or keeping a continuous record of a process or quantity", category: "TECH", difficulty: 7 },
    { word: "OFFLINE", hint: "Not controlled by or directly connected to a computer or the internet", category: "TECH", difficulty: 7 },
    { word: "PROCESS", hint: "Perform a series of mechanical or chemical operations on (something) in order to change or preserve it", category: "GENERAL", difficulty: 7 },
    { word: "SCANNER", hint: "A device for examining, reading, or monitoring something", category: "TECH", difficulty: 7 },
    { word: "UTILITY", hint: "The state of being useful, profitable, or beneficial", category: "GENERAL", difficulty: 7 },
    { word: "VERSION", hint: "A particular form of something differing in certain respects from an earlier form", category: "GENERAL", difficulty: 7 }
];
